### ISSUE TITLE
12-hour Format

### ISSUE THREAD

**Issue by ghost** [vmarci21/php_elapsed-time#1]
1 Weeks ago.

**Comment by vmarci21** [comment]
@semworx: in progress.. Only 1-2 days and I add the code date and time format settings.

**Comment by ghost** [comment]
Thanks, this code is great. But it'll be better if the pluralization will be fixed and also more convenient way to switch from twelve or twenty four hour format. Thanks ;)

**Comment by vmarci21** [comment]
Avalibe in the new code. Thanks your issues. ;)
